spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org.hibernate.SQL: info
app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 3600
    refresh-token-expiration: 2592000
  kakao:
    app-key: ${KAKAO_APP_KEY}
  s3:
    bucket: ${S3_BUCKET}
