create table member (
    id varchar(36) not null,
    email varchar(255) not null,
    name varchar(100) not null,
    nickname varchar(30) not null,
    role varchar(20) not null,
    profile_image_key varchar(512),
    status varchar(20) not null,
    deleted_at timestamp,
    created_at timestamp not null,
    updated_at timestamp,
    created_by varchar(100),
    updated_by varchar(100),
    constraint pk_member primary key (id)
);

create unique index idx_member_email on member (email);

create table social_account (
    id varchar(36) not null,
    member_id varchar(36) not null,
    provider varchar(20) not null,
    provider_id varchar(255) not null,
    email varchar(255),
    created_at timestamp not null,
    updated_at timestamp,
    created_by varchar(100),
    updated_by varchar(100),
    constraint pk_social_account primary key (id),
    constraint uq_social_account_provider_provider_id unique (provider, provider_id),
    constraint fk_social_account_member foreign key (member_id) references member (id)
);

create index idx_social_account_member_id on social_account (member_id);

create table term (
    term_id bigint generated by default as identity not null,
    term_code varchar(50) not null,
    title varchar(100) not null,
    content_url varchar(500),
    version integer not null,
    required_yn varchar(1) not null,
    effective_at timestamp not null,
    created_at timestamp not null,
    updated_at timestamp,
    constraint pk_term primary key (term_id),
    constraint uq_term_code_version unique (term_code, version)
);

create index idx_term_code_effective on term (term_code, effective_at);
