CREATE SEQUENCE IF NOT EXISTS circle_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE;
CREATE SEQUENCE IF NOT EXISTS circle_member_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE;
CREATE SEQUENCE IF NOT EXISTS invitation_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE;
CREATE SEQUENCE IF NOT EXISTS invitation_redemption_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999 CYCLE;
