create table notification
(
    id            bigint generated by default as identity not null,
    channel       varchar(20)                             not null,
    receiver      varchar(255)                            not null,
    event_type    varchar(50)                             not null,
    payload       text                                    not null,
    status        varchar(20)                             not null,
    attempt_count integer                                 not null,
    next_retry_at timestamp,
    sent_at       timestamp,
    failed_at     timestamp,
    fail_reason   varchar(500),
    dedup_key     varchar(255)                            not null,
    created_at    timestamp                               not null,
    updated_at    timestamp,
    created_by    varchar(100),
    updated_by    varchar(100),
    constraint pk_notification primary key (id)
);

create index idx_notification_status_next_retry_at
    on notification (status, next_retry_at);

create unique index uk_notification_dedup_key
    on notification (dedup_key);

create table notification_inbox_item
(
    id                 bigint generated by default as identity not null,
    receiver_member_id varchar(36)                             not null,
    notification_type  varchar(50)                             not null,
    title              varchar(100)                            not null,
    body               varchar(500)                            not null,
    route_type         varchar(30)                             not null,
    circle_id          varchar(36),
    schedule_id        varchar(36),
    event_id           varchar(255)                            not null,
    dedup_key          varchar(255)                            not null,
    read_at            timestamp,
    created_at         timestamp                               not null,
    updated_at         timestamp,
    created_by         varchar(100),
    updated_by         varchar(100),
    constraint pk_notification_inbox_item primary key (id)
);

create index idx_notification_inbox_receiver_created_at
    on notification_inbox_item (receiver_member_id, created_at);

create index idx_notification_inbox_created_at
    on notification_inbox_item (created_at);

create unique index uk_notification_inbox_dedup_key
    on notification_inbox_item (dedup_key);

create table notification_setting
(
    member_id                     varchar(36) not null,
    d7_enabled                    boolean     not null,
    d1_enabled                    boolean     not null,
    dday_enabled                  boolean     not null,
    family_schedule_check_enabled boolean     not null,
    created_at                    timestamp   not null,
    updated_at                    timestamp,
    created_by                    varchar(100),
    updated_by                    varchar(100),
    constraint pk_notification_setting primary key (member_id)
);

create table device_push_token
(
    id                                 bigint generated by default as identity not null,
    member_id                          varchar(36)                             not null,
    token                              varchar(512)                            not null,
    platform                           varchar(20)                             not null,
    os_notification_permission_granted boolean                                 not null,
    app_version                        varchar(50),
    active                             boolean                                 not null,
    last_seen_at                       timestamp                               not null,
    invalidated_at                     timestamp,
    created_at                         timestamp                               not null,
    updated_at                         timestamp,
    created_by                         varchar(100),
    updated_by                         varchar(100),
    constraint pk_device_push_token primary key (id)
);

create index idx_device_push_token_member_active
    on device_push_token (member_id, active);

create unique index uk_device_push_token_token
    on device_push_token (token);

create index idx_notification_inbox_receiver_id
    on notification_inbox_item (receiver_member_id, id desc);