-- Member Agreement 테이블 생성
create table member_agreement (
    member_agreement_id bigint generated by default as identity not null,
    member_id varchar(36) not null,
    term_id bigint not null,
    agreed_at timestamp not null,
    constraint pk_member_agreement primary key (member_agreement_id),
    constraint uk_member_agreement_member_id_term_id unique (member_id, term_id),
    constraint fk_member_agreement_member foreign key (member_id) references member (id),
    constraint fk_member_agreement_term foreign key (term_id) references term (term_id)
);

create index idx_member_agreement_member_id on member_agreement (member_id);
create index idx_member_agreement_term_id on member_agreement (term_id);
