create table withdrawal_log (
    id bigint generated by default as identity not null,
    member_id varchar(36) not null,
    original_email varchar(255),
    reason varchar(500) not null,
    withdrawn_at timestamp not null,
    created_at timestamp not null,
    constraint pk_withdrawal_log primary key (id)
);

create index idx_withdrawal_log_member_id on withdrawal_log (member_id);
