drop table if exists schedule_confirmation;
drop table if exists schedule;
drop sequence if exists schedule_seq;

create sequence if not exists schedule_seq start with 1 increment by 1;

create table schedule (
    schedule_id varchar(19) not null,
    circle_id varchar(21) not null,
    title varchar(30) not null,
    start_date date not null,
    end_date date not null,
    start_time time,
    end_time time,
    need_confirm varchar(1) not null default 'N',
    memo varchar(500),
    created_at timestamp not null,
    updated_at timestamp,
    created_by varchar(100),
    updated_by varchar(100),
    del_yn varchar(1) not null default 'N',
    constraint pk_schedule primary key (schedule_id),
    constraint fk_schedule_circle foreign key (circle_id) references circle (id)
);

create index idx_schedule_circle_sort
    on schedule (circle_id, del_yn, start_date, start_time, schedule_id);

create table schedule_confirmation (
    confirmation_id bigint generated by default as identity not null,
    schedule_id varchar(19) not null,
    member_id varchar(100) not null,
    confirmation_type varchar(30) not null,
    created_at timestamp not null,
    updated_at timestamp,
    created_by varchar(100),
    updated_by varchar(100),
    constraint pk_schedule_confirmation primary key (confirmation_id),
    constraint uq_schedule_confirmation_schedule_member unique (schedule_id, member_id),
    constraint fk_schedule_confirmation_schedule foreign key (schedule_id) references schedule (schedule_id)
);

create index idx_schedule_confirmation_schedule
    on schedule_confirmation (schedule_id);
