create table notification_template
(
    id             bigint generated by default as identity not null,
    event_type     varchar(50)                             not null,
    title_template varchar(100)                            not null,
    body_template  varchar(500)                            not null,
    active         boolean                                 not null,
    created_at     timestamp                               not null,
    updated_at     timestamp,
    created_by     varchar(100),
    updated_by     varchar(100),
    constraint pk_notification_template primary key (id)
);

create unique index uk_notification_template_event_type
    on notification_template (event_type);

insert into notification_template (event_type, title_template, body_template, active, created_at)
values ('CIRCLE_JOIN_COMPLETED', '새 가족이 참여했어요', '{member_name}님이 ''{circle_name}''에 참여했어요.', true, current_timestamp),
       ('SCHEDULE_CREATED', '새 일정이 등록됐어요', '{actor_name}님이 ''{schedule_title}'' 일정을 추가했어요.', true, current_timestamp),
       ('SCHEDULE_DELETED', '일정이 삭제됐어요', '{actor_name}님이 ''{schedule_title}'' 일정을 삭제했어요.', true, current_timestamp),
       ('SCHEDULE_REMINDER_D7', '일주일 후 일정이 있어요', '''{schedule_title}''까지 일주일 남았어요. 미리 준비해보는 건 어떨까요?', true, current_timestamp),
       ('SCHEDULE_REMINDER_D1', '내일, 잊지 말아주세요', '내일은 ''{schedule_title}''이 있는 날이에요. 가족과 함께 준비해봐요.', true, current_timestamp),
       ('SCHEDULE_REMINDER_DDAY_ALL_DAY', '오늘 일정이 있어요', '오늘은 ''{schedule_title}''이 있는 날이에요. 가족과 함께 마음을 나눠보아요.', true, current_timestamp),
       ('SCHEDULE_REMINDER_DDAY_TIMED', '1시간 후 일정이 있어요', '''{schedule_title}'' 일정이 {start_time}에 시작돼요. 미리 확인해 주세요.', true, current_timestamp),
       ('SCHEDULE_CONFIRMED_BY_FAMILY', '가족이 일정을 확인했어요', '{member_name}님이 ''{schedule_title}'' 일정을 확인했어요. 함께 챙길 준비가 되었어요.', true, current_timestamp),
       ('SCHEDULE_CONFIRMATION_REQUESTED', '가족이 일정 확인을 기다리고 있어요', '''{schedule_title}'', 아직 확인 전이에요. 확인 응답을 눌러주세요.', true, current_timestamp);
